<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rte_schema"
 *
 * Auto generated by Extension Builder 2015-06-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Schema.org proprety for RTE',
	'description' => 'Add attributes for schema.org (itemprop, itemscope, itemtype) on RTE',
	'category' => 'misc',
	'author' => 'VANCLOOSTER Mickael',
	'author_email' => 'vanclooster.mickael@gmail.com',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.2',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.0.0-7.9.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);